---
- hosts: zone
  sudo: true

  vars_files:
    - pwd.yml # where db_pwd is defined

  tasks:
    - name: Configure bttv module
      copy: src=files/bttv.conf dest=/etc/modprobe.d/bttv.conf
      notify:
      - reboot

    - name: Install owncloud recommendations
      apt: pkg={{ item }} state=present
      with_items:
      - php5-sqlite
      - vim
      - unzip
      - mysql-server

#    - name: Prepare Owncloud database (MySQL)
#      mysql_db: name=owncloud state=present
#    - mysql_user: name=owncloud password={{db_pwd}} priv=owncloud.*:ALL state=present

    - name: Install Owncloud repository key
      apt_key: url=http://download.opensuse.org/repositories/isv:ownCloud:community/xUbuntu_12.04/Release.key state=present
    - name: Install Owncloud repository
      copy: src=files/owncloud.list dest=/etc/apt/sources.list.d/owncloud.list
    - name: Install the latest Owncloud package
      apt: pkg=owncloud state=latest update_cache=yes cache_valid_time=86400
      notify:
      - restart apache

    - name: Create motion folder in Owncloud
      file: path=/var/www/owncloud/data/{{user}}/files/motion state=directory
    - name: Set folder permissions
      file: path=/usr/share/owncloud state=directory owner=www-data group=www-data mode=0775 recurse=yes

    - name: Install motion and friends
      apt: pkg={{ item }}
      with_items:
      - motion
      - ffmpeg
    - name: Configure motion permissions
      user: name=motion groups="www-data,video"

    - name: Configure motion
      copy: src=files/{{ item }}.conf dest=/etc/motion/{{ item }}.conf
      with_items:
      - motion
      - thread1
      - thread2
      - thread3
      - thread4
      - thread5
      - thread6
      - thread7
      - thread8
      - thread9
      - thread10
      - thread11
      notify:
        - restart motion
    - name: Patch motion startup script
      copy: src=files/motion-init dest=/etc/init.d/motion
    - file: path=/etc/init.d/motion mode=0755

    - name: Enable motion
      copy: src=files/motion dest=/etc/default/motion
      notify:
        - restart motion

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
    - name: restart motion
      service: name=motion state=restarted
    - name: reboot
      command: /sbin/reboot -t now
