---
- hosts: zone
  sudo: true

  vars_files:
    - pwd.yml # where db_pwd is defined

  tasks:
    # https://bluecherry.zendesk.com/entries/235174-Using-the-Bluecherry-hardware-compression-open-source-Linux-drivers-MPEG-4-H-264-
    - name: Download Bluecherry driver
      command: git clone http://github.com/bluecherrydvr/solo6x10.git /usr/local/src/solo6x10 creates=/usr/local/src/solo6x10
      tags: setup

    - name: Compile Bluecherry driver
      shell: cd /usr/local/src/solo6x10 && make creates=/etc/modprobe.d/solo6x10.conf
      tags: setup

    - name: Install Bluecherry driver
      shell: cd /usr/local/src/solo6x10 && make install && depmod -a creates=/etc/modprobe.d/solo6x10.conf
      tags: setup
      notify: reboot

    - name: Copy solo modprobe config
      copy: src=files/solo6x10.conf dest=/etc/modprobe.d/solo6x10.conf
      tags: setup
      notify: reboot

    - name: Configure bttv module
      copy: src=files/bttv.conf dest=/etc/modprobe.d/bttv.conf
      tags: setup
      notify: reboot

    - name: Install owncloud recommendations
      apt: pkg={{ item }} state=present
      with_items:
      - php5-sqlite
      - php5-ldap
      - php-apc
      - vim
      - unzip
      - mysql-server

#    - name: Prepare Owncloud database (MySQL)
#      mysql_db: name=owncloud state=present
#    - mysql_user: name=owncloud password={{db_pwd}} priv=owncloud.*:ALL state=present

#    - name: Install Owncloud repository key
#      apt_key: url=http://download.opensuse.org/repositories/isv:ownCloud:community/xUbuntu_12.04/Release.key state=present
    - name: Install Owncloud repository
      copy: src=files/owncloud.list dest=/etc/apt/sources.list.d/owncloud.list

    - name: Install the latest Owncloud package
      apt: pkg=owncloud state=present update_cache=yes cache_valid_time=86400
      notify:
      - restart apache

    - name: Configure Owncloud
      copy: src=files/owncloud-config.php dest=/var/www/owncloud/config/config.php

    - name: Configure Apache modules
      raw: a2enmod rewrite; a2enmod headers
      notify:
      - restart apache

    - name: Configure Apache default site
      copy: src=files/apache2/sites-default dest=/etc/apache2/sites-available/default
      notify:
      - restart apache

    - name: Configure Apache default site (SSL)
      copy: src=files/apache2/sites-default-ssl dest=/etc/apache2/sites-available/default-ssl
      notify:
      - restart apache

    - name: Configure PHP
      copy: src=files/apache2/php.ini dest=/etc/php5/apache2/php.ini
      notify:
      - restart apache

    - name: Create motion folder in Owncloud
      file: path=/var/www/owncloud/data/{{user}}/files/motion state=directory

    - name: Set folder permissions
      file: path=/var/www/owncloud state=directory owner=www-data group=www-data mode=0770 recurse=yes

    - name: Install motion and friends
      apt: pkg={{ item }}
      with_items:
      - motion
      - ffmpeg
    - name: Configure motion permissions
      user: name=motion groups="www-data,video"

    - name: Configure motion
      copy: src=files/{{ item }}.conf dest=/etc/motion/{{ item }}.conf
      tags: setup
      with_items:
      - motion
      - thread1
      - thread2
      - thread3
      - thread4
      - thread5
      - thread6
      - thread7
      - thread8
      - thread9
      - thread10
      - thread11
      tags: setup
      notify:
        - restart motion

    - name: Patch motion startup script
      tags: setup
      copy: src=files/motion-init dest=/etc/init.d/motion
    - file: path=/etc/init.d/motion mode=0755

    - name: Enable motion
      copy: src=files/motion dest=/etc/default/motion
      notify:
        - restart motion

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
    - name: restart motion
      service: name=motion state=restarted
    - name: reboot
      command: /sbin/reboot -t now
